[package]
name = "phenolphthalein"
version = "0.1.0"
authors = ["Matt Windsor <nihilistmatt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
libc = "0.2"
crossbeam = "0.8.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"

[build-dependencies]
cc = "1.0"

[profile.release]
debug = true